/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as XaiRouteImport } from './routes/xai'
import { Route as SentimentRouteImport } from './routes/sentiment'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReportRouteImport } from './routes/report'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LabRouteImport } from './routes/lab'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ClvRouteImport } from './routes/clv'
import { Route as ChurnRouteImport } from './routes/churn'
import { Route as BasketRouteImport } from './routes/basket'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const XaiRoute = XaiRouteImport.update({
  id: '/xai',
  path: '/xai',
  getParentRoute: () => rootRouteImport,
} as any)
const SentimentRoute = SentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ClvRoute = ClvRouteImport.update({
  id: '/clv',
  path: '/clv',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurnRoute = ChurnRouteImport.update({
  id: '/churn',
  path: '/churn',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketRoute = BasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/basket': typeof BasketRoute
  '/churn': typeof ChurnRoute
  '/clv': typeof ClvRoute
  '/customers': typeof CustomersRoute
  '/forecast': typeof ForecastRoute
  '/lab': typeof LabRoute
  '/marketing': typeof MarketingRoute
  '/report': typeof ReportRoute
  '/sales': typeof SalesRoute
  '/score': typeof ScoreRoute
  '/sentiment': typeof SentimentRoute
  '/xai': typeof XaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/basket': typeof BasketRoute
  '/churn': typeof ChurnRoute
  '/clv': typeof ClvRoute
  '/customers': typeof CustomersRoute
  '/forecast': typeof ForecastRoute
  '/lab': typeof LabRoute
  '/marketing': typeof MarketingRoute
  '/report': typeof ReportRoute
  '/sales': typeof SalesRoute
  '/score': typeof ScoreRoute
  '/sentiment': typeof SentimentRoute
  '/xai': typeof XaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/basket': typeof BasketRoute
  '/churn': typeof ChurnRoute
  '/clv': typeof ClvRoute
  '/customers': typeof CustomersRoute
  '/forecast': typeof ForecastRoute
  '/lab': typeof LabRoute
  '/marketing': typeof MarketingRoute
  '/report': typeof ReportRoute
  '/sales': typeof SalesRoute
  '/score': typeof ScoreRoute
  '/sentiment': typeof SentimentRoute
  '/xai': typeof XaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/basket'
    | '/churn'
    | '/clv'
    | '/customers'
    | '/forecast'
    | '/lab'
    | '/marketing'
    | '/report'
    | '/sales'
    | '/score'
    | '/sentiment'
    | '/xai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/basket'
    | '/churn'
    | '/clv'
    | '/customers'
    | '/forecast'
    | '/lab'
    | '/marketing'
    | '/report'
    | '/sales'
    | '/score'
    | '/sentiment'
    | '/xai'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/basket'
    | '/churn'
    | '/clv'
    | '/customers'
    | '/forecast'
    | '/lab'
    | '/marketing'
    | '/report'
    | '/sales'
    | '/score'
    | '/sentiment'
    | '/xai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BasketRoute: typeof BasketRoute
  ChurnRoute: typeof ChurnRoute
  ClvRoute: typeof ClvRoute
  CustomersRoute: typeof CustomersRoute
  ForecastRoute: typeof ForecastRoute
  LabRoute: typeof LabRoute
  MarketingRoute: typeof MarketingRoute
  ReportRoute: typeof ReportRoute
  SalesRoute: typeof SalesRoute
  ScoreRoute: typeof ScoreRoute
  SentimentRoute: typeof SentimentRoute
  XaiRoute: typeof XaiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/xai': {
      id: '/xai'
      path: '/xai'
      fullPath: '/xai'
      preLoaderRoute: typeof XaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentiment': {
      id: '/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof SentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clv': {
      id: '/clv'
      path: '/clv'
      fullPath: '/clv'
      preLoaderRoute: typeof ClvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/churn': {
      id: '/churn'
      path: '/churn'
      fullPath: '/churn'
      preLoaderRoute: typeof ChurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basket': {
      id: '/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof BasketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BasketRoute: BasketRoute,
  ChurnRoute: ChurnRoute,
  ClvRoute: ClvRoute,
  CustomersRoute: CustomersRoute,
  ForecastRoute: ForecastRoute,
  LabRoute: LabRoute,
  MarketingRoute: MarketingRoute,
  ReportRoute: ReportRoute,
  SalesRoute: SalesRoute,
  ScoreRoute: ScoreRoute,
  SentimentRoute: SentimentRoute,
  XaiRoute: XaiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
